# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 11:07
from __future__ import unicode_literals

from django.db import migrations, models
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command('loaddata', 'initial.json', app_label='foobar')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RunPython(load_fixtures),
    ]
